#!/bin/sh
#SBATCH --time=7:30:00    # walltime
#SBATCH --nodes=1
#SBATCH --partition=test
#SBATCH --mem-per-cpu=2000
#SBATCH --ntasks-per-node=32  # number of processor cores (i.e. tasks)
#SBATCH --job-name=SeisIOTest   # job name
#SBATCH --output=out.dat      # output file name
#SBATCH --error=err.dat      # error File
#
#
##### These are shell commands: Please configure them
date
module purge
module load intel/17.0.4-fasrc01 openmpi/3.1.3-fasrc01
module load postgresql/10.5-fasrc01
conda activate obspy

sh run_rover.sh
sh run_obspy.sh
sh run_SeisIO.sh
echo all process has been done.
